<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

  <xsl:output method="text" />

  <xsl:include href="common.xslt" />
  
  <!-- Generates SQL script for adding file groups and files -->

  <!-- Entry point -->
  <xsl:template match="/">

    <xsl:call-template name="sqlComment">
      <xsl:with-param name="commentText" select="'Autogenerated by filegroups.xslt'" />
    </xsl:call-template>
    
    <!-- Process all filegroups -->
    <xsl:apply-templates select="//filegroups/filegroup" />

    <!-- Process log files -->
    <xsl:call-template name="sqlComment">
      <xsl:with-param name="commentText" select="'LogFiles'" />
    </xsl:call-template>
    <xsl:apply-templates select="//logs/file" mode="log"/>

  </xsl:template>

  <xsl:template match="filegroup">
    
    <!-- Add the filegroup to database -->
    <xsl:call-template name="sqlComment">
      <xsl:with-param name="commentText">
        <xsl:text>Filegroup </xsl:text>
        <xsl:value-of select="@name"/>
      </xsl:with-param>
    </xsl:call-template>

    <!-- Skip the PRIMARY filegroup (it's already created) -->
    <xsl:if test="@name!='PRIMARY'">
      <xsl:text>ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [</xsl:text>
      <xsl:value-of select="@name"/>
      <xsl:text>];&#xa;GO&#xa;&#xa;</xsl:text>
    </xsl:if>
    
    <!-- Add all the files to the filegroup -->
    <xsl:apply-templates select="file" mode="data" />
    
  </xsl:template>

  <xsl:template match="file" mode="log">
    <xsl:text>ALTER DATABASE [$(DatabaseName)] ADD LOG FILE (NAME=N'</xsl:text>
    <xsl:value-of select="@name" />
    <xsl:text>', FILENAME = N'$(LogPath)\$(DatabaseName)_</xsl:text>
    <xsl:value-of select="@name" />
    <xsl:text>.ldf</xsl:text>
    <xsl:text>')</xsl:text>
    <xsl:text>&#xa;GO&#xa;&#xa;</xsl:text>
  </xsl:template>
  
  <xsl:template match="file" mode="data">
    <xsl:text>ALTER DATABASE [$(DatabaseName)] ADD FILE (NAME=N'</xsl:text>
    <xsl:value-of select="@name" />
    <xsl:text>', FILENAME = N'$(DataPath)\$(DatabaseName)_</xsl:text>
    <xsl:value-of select="@name" />
    <xsl:choose>
      <xsl:when test="../@name='PRIMARY'">
        <xsl:text>.mdf</xsl:text>
      </xsl:when>
      <xsl:otherwise>
        <xsl:text>.ndf</xsl:text>
      </xsl:otherwise>
    </xsl:choose>
    <xsl:text>') TO FILEGROUP [</xsl:text>
    <xsl:value-of select="../@name" />
    <xsl:text>]&#xa;GO&#xa;&#xa;</xsl:text>
  </xsl:template>
  
</xsl:stylesheet>  
