<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

  <xsl:output method="text" />

  <xsl:include href="common.xslt" />
  
  <!-- Generates SQL script for configuring files -->

  <!-- Entry point -->
  <xsl:template match="/">

    <xsl:call-template name="sqlComment">
      <xsl:with-param name="commentText" select="'Autogenerated by confiles.xslt'" />
    </xsl:call-template>

    <!-- Process all data files -->
    <xsl:apply-templates select="//filegroup/file" mode="data"/>

    <!-- Process all log files -->
    <xsl:apply-templates select="//logs/file" mode="log"/>

  </xsl:template>

  <xsl:template match="file" mode="data">
    <xsl:text>ALTER DATABASE [$(DatabaseName)] MODIFY FILE (NAME=N'</xsl:text>
    <xsl:value-of select="@name" />
    <xsl:text>', SIZE = $(FileSize), MAXSIZE = $(MaxFileSize), FILEGROWTH = $(FileGrowth))</xsl:text>
    <xsl:text>&#xa;GO&#xa;&#xa;</xsl:text>
  </xsl:template>
  
  <xsl:template match="file" mode="log">
    <xsl:text>ALTER DATABASE [$(DatabaseName)] MODIFY FILE (NAME=N'</xsl:text>
    <xsl:value-of select="@name" />
    <xsl:text>', SIZE = $(LogFileSize), MAXSIZE = $(MaxLogFileSize), FILEGROWTH = $(LogFileGrowth))</xsl:text>
    <xsl:text>&#xa;GO&#xa;&#xa;</xsl:text>
  </xsl:template>

</xsl:stylesheet>  
